stock:
  inner:
    - sh000001
    - sz399001
  outer: # 外盛
    - int_dja # 道球期
    - int_nasdaq # 纳斯达克
    - int_hangseng # 恒生
    - int_nikkei # 日经指数
    - b_FSSTI
  marketUrl: https://hq.sinajs.cn/list=
  blockUrl: https://vip.stock.finance.sina.com.cn/q/view/newSinaHy.php